services:
  db:
    image: postgres:16
    container_name: autobackup-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: autobackup_db
      POSTGRES_USER: autobackup
      POSTGRES_PASSWORD: autobackup
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:

